version: "3.3"

services:
  booking-system:
    image: booking-system:dev
    command: ./scripts/wait-for-it.sh booking-system.db:5432 -- npm run dev
    ports:
      - "3000:3000"
    environment:
      - LOG_LEVEL=debug
      - NODE_ENV=development
