# This work flow happens when pushing to branches except
# master and release branch
name: Test

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '!master'
      - '!release'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 14.16.0
        uses: actions/setup-node@v2
        with:
          node-version: "14.16.0"

      - name: Test
        run: npm run compose:test
