# This work flow happens when pushing to branches except
# master and release branch
name: Test workflow

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '!master'
      - '!release'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 12.16.3
        uses: actions/setup-node@v1
        with:
          node-version: "12.16.3"

      - name: Install pacakges
        run: npm install

      - name: Test
        run: npm run compose:test

      - name: Clean build
        run: |
          npm run clean
          npm run start:build
